import type { Metadata } from "next";

import "./globals.css";
import { ContentLayout } from "./content.layout";
import { Lexend } from "next/font/google"; // Add this import

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${lexend.className} antialiased`}>
        <ContentLayout> {children}</ContentLayout>
      </body>
    </html>
  );
}
